// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBreHaIf7lseSc1EytN4H-muB2CVYDrw1I',
    appId: '1:1002369640246:web:729bd2a4d1c45bea4df597',
    messagingSenderId: '1002369640246',
    projectId: 'eindopdracht-f0cf9',
    authDomain: 'eindopdracht-f0cf9.firebaseapp.com',
    storageBucket: 'eindopdracht-f0cf9.appspot.com',
    measurementId: 'G-QVSF75WLFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB320IH3kRieswSWr9XUFejJ3KYqsp-MJw',
    appId: '1:1002369640246:android:d470559f3d71def64df597',
    messagingSenderId: '1002369640246',
    projectId: 'eindopdracht-f0cf9',
    storageBucket: 'eindopdracht-f0cf9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX0dXvsqCmiR29kN8W8FzL0q_SojbFzcI',
    appId: '1:1002369640246:ios:78c3d1a0b936965c4df597',
    messagingSenderId: '1002369640246',
    projectId: 'eindopdracht-f0cf9',
    storageBucket: 'eindopdracht-f0cf9.appspot.com',
    iosBundleId: 'com.example.dailyPhoto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX0dXvsqCmiR29kN8W8FzL0q_SojbFzcI',
    appId: '1:1002369640246:ios:78c3d1a0b936965c4df597',
    messagingSenderId: '1002369640246',
    projectId: 'eindopdracht-f0cf9',
    storageBucket: 'eindopdracht-f0cf9.appspot.com',
    iosBundleId: 'com.example.dailyPhoto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBreHaIf7lseSc1EytN4H-muB2CVYDrw1I',
    appId: '1:1002369640246:web:bc9a43d0e7581ce54df597',
    messagingSenderId: '1002369640246',
    projectId: 'eindopdracht-f0cf9',
    authDomain: 'eindopdracht-f0cf9.firebaseapp.com',
    storageBucket: 'eindopdracht-f0cf9.appspot.com',
    measurementId: 'G-S1T70P8C1P',
  );

}