name: daily_photo
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  geolocator: ^8.0.1
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  table_calendar: ^3.0.8
  camera: ^0.10.5+9
  firebase_storage: ^11.7.2
  geocoding: ^2.0.1
  flutter:
    sdk: flutter
  intl: ^0.19.0
  dev: ^1.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon/calenderCamera.png"